CREATE TABLE IF NOT EXISTS songs (
  id SERIAL PRIMARY KEY,
  coverurl TEXT,
  name TEXT,
  artist TEXT,
  title TEXT,
  album TEXT,
  genre TEXT,
  year TEXT,
  category TEXT,
  bitrate TEXT,
  bitrate320 TEXT,
  bitrate192 TEXT,
  bitrate128 TEXT,
  size TEXT,
  size320 TEXT,
  size192 TEXT,
  size128 TEXT,
  link TEXT,
  url TEXT,
  url320 TEXT,
  url192 TEXT,
  url128 TEXT,
  duration TEXT,
  lyrics TEXT,
  lyricstimestamp TEXT,
  permalink TEXT,
  permalinkartist TEXT,
  permalinktitle TEXT,
  upl TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  view INTEGER DEFAULT 0
);
